"""Каталог идей — стартовый набор, сгруппированный по кластерам."""

from __future__ import annotations

from typing import Any, Dict, List

# status: needs_action | connected | running
# tier: flagship | strong | experimental | watch
# cluster: platform | data | b2b | marketplace | content | referral | product

SEED_IDEAS: List[Dict[str, Any]] = [
    # ── Флагман: одна платформа вместо пяти отдельных ботов ──
    {
        "slug": "oracle-platform",
        "title": "«Оракул» — подписка Stars (гадания + совместимость + хиромантия + отношения)",
        "category": "платформа",
        "cluster": "platform",
        "tier": "flagship",
        "status": "needs_action",
        "action_required": "1 бот, 4 модуля: расклад/гороскоп, совместимость по датам, фото ладони (Vision), советы по знакомствам",
        "potential_rub": "199–499 ₽/мес × удержание",
        "automation_pct": 96,
        "note": "Объединяет: гадания, совместимость, хиромантия, «как подкатить». Один биллинг, общая воронка",
    },
    {
        "slug": "life-spheres-matrix",
        "title": "12 сфер жизни × идеи бизнеса в каждой",
        "category": "мета",
        "cluster": "data",
        "tier": "flagship",
        "status": "needs_action",
        "action_required": "Таблица: здоровье, деньги, любовь, дом, дети… → продукт/бот/рефералка в каждой",
        "potential_rub": "мозг всей системы",
        "automation_pct": 90,
        "note": "Каркас для дашборда и контент-плана. Не отдельный продукт — основа приоритизации",
    },
    {
        "slug": "spending-intelligence",
        "title": "Кто за что платит без раздумий (по возрастам и моментам)",
        "category": "мета",
        "cluster": "data",
        "tier": "flagship",
        "status": "needs_action",
        "action_required": "Собрать матрицу: 14–17 / 18–25 / 25–35 / 35–50 / 50+ → категории импульсных трат",
        "potential_rub": "питает все боты и воронки",
        "automation_pct": 85,
        "note": "Включает «малолетки и игры», «список возрастов». DATA-слой — не продаётся напрямую",
    },
    {
        "slug": "biz-automation-matcher",
        "title": "«Опиши бизнес» → каталог готовых автоматизаций + цена",
        "category": "SaaS",
        "cluster": "b2b",
        "tier": "flagship",
        "status": "needs_action",
        "action_required": "База 30–50 решений (бот записи, ответы на отзывы, смета…) + калькулятор в TG/сайте",
        "potential_rub": "5–50 тыс. ₽ / внедрение",
        "automation_pct": 80,
        "note": "Сильнейшая B2B-идея из списка. Продаёшь то, что уже умеешь собирать",
    },
    {
        "slug": "referral-hub",
        "title": "Единое приложение — все рефералки и CPA",
        "category": "платформа",
        "cluster": "referral",
        "tier": "flagship",
        "status": "needs_action",
        "action_required": "Список офферов + трекинг ссылок + напоминания + дашборд (расширение Центра доходов)",
        "potential_rub": "сумма всех партнёрок",
        "automation_pct": 92,
        "note": "«База рефералов — одно приложение». Замыкает цикл с дашбордом",
    },
    {
        "slug": "trend-scout-engine",
        "title": "Разведка идей: тренды → монетизация → запуск",
        "category": "мета",
        "cluster": "data",
        "tier": "flagship",
        "status": "running",
        "action_required": "",
        "potential_rub": "питает весь конвейер",
        "automation_pct": 95,
        "note": "Wordstat/Trends → оценка → бот/сайт/чат → в реестр. Минимум участия пользователя",
    },
    # ── B2B и автоматизация ──
    {
        "slug": "biz-plan-budget",
        "title": "Подбор бизнеса и плана под бюджет",
        "category": "SaaS",
        "cluster": "b2b",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "10–20 шаблонов планов + квиз «бюджет / время / навыки»",
        "potential_rub": "990–4 990 ₽ / план или lead magnet",
        "automation_pct": 88,
    },
    {
        "slug": "wb-card-bot",
        "title": "Карточки WB/Ozon для селлеров",
        "category": "SaaS",
        "cluster": "b2b",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "ИП/самозанятость + оплата Stars/ЮKassa",
        "potential_rub": "59–299 ₽ / карточка",
        "automation_pct": 90,
    },
    {
        "slug": "review-reply-bot",
        "title": "Ответы на отзывы WB/Ozon",
        "category": "SaaS",
        "cluster": "b2b",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "MVP бота + первый тестовый селлер",
        "potential_rub": "490 ₽ / 100 ответов",
        "automation_pct": 95,
    },
    {
        "slug": "selfemployed-receipt-bot",
        "title": "Чеки для самозанятых",
        "category": "бот",
        "cluster": "b2b",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Шаблоны PDF + Stars",
        "potential_rub": "49 ₽ / чек",
        "automation_pct": 98,
    },
    {
        "slug": "tg-b2b-bots",
        "title": "B2B боты (запись, заявки)",
        "category": "услуга",
        "cluster": "b2b",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "1 пилотный клиент (мастер / сервис)",
        "potential_rub": "5–15 тыс. ₽/мес",
        "automation_pct": 70,
    },
    # ── Биржи и посредники ──
    {
        "slug": "lead-exchange",
        "title": "Биржа лидов — приведи клиента, получи %",
        "category": "marketplace",
        "cluster": "marketplace",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "1 вертикаль (ремонт / beauty / юрист) + TG-бот заявок + % с сделки",
        "potential_rub": "5–20% с чека",
        "automation_pct": 75,
        "note": "«Помощь приведения клиентов другим людям»",
    },
    {
        "slug": "agent-deal-network",
        "title": "Сеть исполнителей — задачи за % от сделки",
        "category": "marketplace",
        "cluster": "marketplace",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Роли: ты — координатор, другие — продажи/монтаж/контент. Договор + трекинг",
        "potential_rub": "10–30% маржа координатора",
        "automation_pct": 65,
        "note": "«Расширение через других людей»",
    },
    {
        "slug": "avito-free-scanner",
        "title": "Сканер «бесплатно» на Авито (халява для перепродажи / контента)",
        "category": "инструмент",
        "cluster": "marketplace",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Парсер + фильтр «отдам даром» + алерт в TG по городу",
        "potential_rub": "перепродажа + контент «нашёл халяву»",
        "automation_pct": 93,
    },
    # ── Контент и трафик ──
    {
        "slug": "service-seo-funnel",
        "title": "1000+ страниц услуг + авто-видео + TG-канал + воронка",
        "category": "контент",
        "cluster": "content",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Шаблон landing + генератор видео + один TG на нишу (сначала 1, не 1000)",
        "potential_rub": "SEO + affiliate + Stars",
        "automation_pct": 90,
        "note": "Масштабировать после первой рабочей ниши",
    },
    {
        "slug": "content-factory",
        "title": "Конвейер Shorts → Telegram",
        "category": "контент",
        "cluster": "content",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "OAuth YouTube/TikTok (один раз)",
        "potential_rub": "трафик → продажи",
        "automation_pct": 88,
    },
    {
        "slug": "music-track-promo",
        "title": "Продвижение своих треков (стримы → роялти)",
        "category": "контент",
        "cluster": "content",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Авто-Shorts/Reels с фрагментами треков → VK, YouTube, TikTok. UTM/ссылки на площадки",
        "potential_rub": "рост прослушиваний от лейбла",
        "automation_pct": 88,
        "note": "Договор с муз. компанией. Конвейер: видео + мемы + картинки → все соцсети",
    },
    {
        "slug": "watch-earn-platform",
        "title": "«Смотри рекламу — получай» (TG Mini App / сайт)",
        "category": "платформа",
        "cluster": "content",
        "tier": "watch",
        "status": "needs_action",
        "action_required": "Модель: рекламодатель платит → 40% пользователю, 60% тебе. Яндекс РСЯ / прямые CPA. Без «плати за клик»",
        "potential_rub": "маржа с оборота рекламы",
        "automation_pct": 92,
        "note": "AdMob/РСЯ запрещают платить за клики — только rewarded video внутри своего контента",
    },
    # ── Рефералки и CPA ──
    {
        "slug": "yandex-browser-partner",
        "title": "Партнёрка Яндекс Браузер",
        "category": "рефералка",
        "cluster": "referral",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Регистрация на partner.browser.yandex.ru, модерация, самозанятость",
        "potential_rub": "до 600 ₽ / установка",
        "automation_pct": 85,
    },
    {
        "slug": "yandex-distribution",
        "title": "Яндекс Дистрибуция (Маркет, Директ)",
        "category": "рефералка",
        "cluster": "referral",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Аккаунт distribution.yandex.ru + выбор офферов",
        "potential_rub": "до 10 000 ₽ / клиент Директа",
        "automation_pct": 80,
    },
    {
        "slug": "yandex-eda-courier",
        "title": "Яндекс Еда — приведи курьера",
        "category": "рефералка",
        "cluster": "referral",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Подключение реф. программы Edа",
        "potential_rub": "до 39 000 ₽ / курьер",
        "automation_pct": 70,
    },
    {
        "slug": "ozon-affiliate",
        "title": "Ozon Blogger / подборки",
        "category": "рефералка",
        "cluster": "referral",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Ozon Blogger + самозанятость для вывода",
        "potential_rub": "5–50 тыс. ₽/мес",
        "automation_pct": 90,
    },
    {
        "slug": "osago-cpa",
        "title": "Бот / виджет ОСАГО (CPA)",
        "category": "рефералка",
        "cluster": "referral",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Регистрация в Polis812 / Pampadu",
        "potential_rub": "500–2 000 ₽ / полис",
        "automation_pct": 88,
    },
    {
        "slug": "credit-card-cpa",
        "title": "CPA: кредитные карты и банки (легальная рефералка)",
        "category": "рефералка",
        "cluster": "referral",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Leadgid / Admitad / банковские CPA. Контент «сравнение карт», не самореферал",
        "potential_rub": "500–5 000 ₽ / одобрение",
        "automation_pct": 85,
        "note": "«Кредит банк» — только белая модель: обзоры + CPA, не замкнутый круг",
    },
    {
        "slug": "cpa-micro-tasks",
        "title": "Микро-задания с CPA-выплатой (легальная модель)",
        "category": "рефералка",
        "cluster": "referral",
        "tier": "watch",
        "status": "needs_action",
        "action_required": "Только реальные задания для пользователя (установка, опрос). Без «плати сам себе»",
        "potential_rub": "маржа CPA − выплата исполнителю",
        "automation_pct": 75,
        "note": "Рефрейм «задание за деньги + реферал». Серая схема «регистрация карты → плати себе» = бан",
    },
    # ── Продукты и боты ──
    {
        "slug": "shed-kit-sales",
        "title": "Комплект хозблок 3×3 (Avito / цифра)",
        "category": "продукт",
        "cluster": "product",
        "tier": "strong",
        "status": "connected",
        "action_required": "",
        "potential_rub": "15–60 тыс. ₽ / продажа",
        "automation_pct": 75,
        "revenue_today": 0,
        "revenue_month": 0,
        "note": "PDF, 3MF, видео v5 уже собраны",
    },
    {
        "slug": "shed-estimate-bot",
        "title": "Бот «Смета хозблока» + Ozon",
        "category": "бот",
        "cluster": "product",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Связать расчёт из кода с TG-ботом",
        "potential_rub": "affiliate + Stars",
        "automation_pct": 92,
    },
    {
        "slug": "english-greenhouse",
        "title": "Комплект «Английская теплица» (как хозблок)",
        "category": "продукт",
        "cluster": "product",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Спека + 3MF/PDF + видео сборки. Переиспользовать pipeline хозблока",
        "potential_rub": "20–80 тыс. ₽ / комплект",
        "automation_pct": 78,
        "note": "Физический продукт: каркас + поликарбонат, продажа Avito + цифра",
    },
    {
        "slug": "dacha-astro-bot",
        "title": "Telegram «Дача / совет дня»",
        "category": "бот",
        "cluster": "platform",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "BotFather + Stars. Можно модуль в «Оракул» или отдельная ниша",
        "potential_rub": "99–399 ₽ / подписка",
        "automation_pct": 95,
    },
    {
        "slug": "pdd-premium-bot",
        "title": "ПДД Premium (экзамен ГИБДД)",
        "category": "бот",
        "cluster": "platform",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "База билетов + Stars",
        "potential_rub": "149–399 ₽/мес",
        "automation_pct": 95,
    },
    {
        "slug": "greeting-video",
        "title": "Поздравительные видео из фото",
        "category": "SaaS",
        "cluster": "content",
        "tier": "strong",
        "status": "needs_action",
        "action_required": "Шаблоны ffmpeg + оплата",
        "potential_rub": "399 ₽ / ролик",
        "automation_pct": 95,
    },
]

TIER_LABELS = {
    "flagship": "флагман",
    "strong": "сильная",
    "experimental": "уточнить",
    "watch": "осторожно",
}
